### ISSUE TITLE
Ajout des balises communes 

### ISSUE THREAD

**Issue by Corentinfaye** [chartes/dico-topo#12]
Messieurs @canteaut @architexte, 

Certains cas particuliers trouvés dans la balise  `localisation` demande une certaine expertise pour savoir ce que je dois faire avec :

- Cas des notions cantons, arrondissement qui sont suivi du nom d'une ville doivent-ils être ajouter comme des communes ou non 

- On trouve aussi régulièrement la notion de "près de" qui peut être suivi de plein de données aussi bien une commune qu'un hameau ou autre donc il semble judicieux que ces données soient contrôlées. 

- Il existe une ambiguité par rapport au cas qui précise un lieu par un site naturel Il peut s'agir d'un site naturel d'une commune comme Laruns qui est une commune du département :

  <article id="DT64-02401" pg="69">
    <vedette><sm>Gave de Bious (Le),</sm></vedette>
    <definition><typologie>ruisseau</typologie> qui descend des <localisation>montagnes de Laruns</localisation> 

Mais il peut aussi s'agir d'un nom qui ne soit pas lié aux communes : 

`<article id="DT64-04057" pg="119">
    <vedette><sm>Mouscle (La),</sm></vedette>
    <definition><typologie>ruisseau</typologie> qui sort du <localisation>bois de Mourle</localisation>`

Donc il est probable

**Comment by canteaut** [comment]
Bonjour,
Quelques éléments de réponse ci-dessous :
>
>  *
>
>     Cas des notions cantons, arrondissement qui sont suivi du nom
>     d'une ville doivent-ils être ajouter comme des communes ou non
>
Je ne suis pas sûr de comprendre. Pourriez-vous donner un exemple ?
>
>  *
>
>     On trouve aussi régulièrement la notion de "près de" qui peut être
>     suivi de plein de données aussi bien une commune qu'un hameau ou
>     autre donc il semble judicieux que ces données soient contrôlées.
>
Oui, liste à contrôler. Probablement des communes dans la majorité des 
cas, mais ce n'est pas certain. La meilleure vérification consisterait 
sans doute à regarder quelle(s) vedettes  correspondent à ces noms : 
nous récupérerions alors le n° INSEE qui leur est attaché, qu'il 
s'agisse d'une commune ou d'un hameau localisé dans une commune ; en 
revanche, il faudrait vérifier, car nous aurons en ce cas de nombreux 
cas d'homonymie. Et l'ensemble est sans doute à faire tout à la fin, 
quand tous les hameaux localisés se seront vus attribués un n° INSEE.
>
>  *
>
>     Il existe une ambiguité par rapport au cas qui précise un lieu par
>     un site naturel Il peut s'agir d'un site naturel d'une commune
>     comme Laruns qui est une commune du département :
>
>     Gave de Bious (Le), ruisseau qui descend des montagnes de Laruns
>
> Mais il peut aussi s'agir d'un nom qui ne soit pas lié aux communes :
>
> |<article id="DT64-04057" pg="119"> <vedette><sm>Mouscle 
> (La),</sm></vedette> <definition><typologie>ruisseau</typologie> qui 
> sort du <localisation>bois de Mourle</localisation>|
>
A mon sens, c'est le même cas que précédemment : la localisation est une 
commune ou non... Mais il n'est pas certain que cela se rencontre dans 
tous les dictionnaires et cela concerne certains types de lieu (bois, 
forêts, rivières, voies de communication ; malheureusement, le 
vocabulaire des DT en la matière est trop peu normalisé pour qu'on s'y 
retrouve aisément).

Je ne sais si tout ceci vous aide ; n'hésitez pas à me recontacter.

Olivier Canteaut

**Comment by Corentinfaye** [comment]
Bonjour, 

> Je ne suis pas sûr de comprendre. Pourriez-vous donner un exemple ?

Je me suis mal exprimé, je vous fais suivre l'exemple d'un canton et d'un arrondissement. La question que je me pose est que le canton et l'arrondissement mentionné correspond à un autre niveau administrative donc on ne parle pas directement de la commune mais cela peut-être lié à elle.
 
` <definition><localisation>canton de Lembeye</localisation>.</definition>`

`<definition><localisation>arrondissement d’Oloron</localisation>`
    

> Oui, liste à contrôler. Probablement des communes dans la majorité des
cas, mais ce n'est pas certain. La meilleure vérification consisterait
sans doute à regarder quelle(s) vedettes  correspondent à ces noms :
nous récupérerions alors le n° INSEE qui leur est attaché, qu'il
s'agisse d'une commune ou d'un hameau localisé dans une commune ; en
revanche, il faudrait vérifier, car nous aurons en ce cas de nombreux
cas d'homonymie. Et l'ensemble est sans doute à faire tout à la fin,
quand tous les hameaux localisés se seront vus attribués un n° INSEE.

Oui, je suis d'accord, un contrôle de ces entrées sur les vedettes du tableau de correction doit permettre de vérifier si c'est une commune ou non mais avec les possibles différences de graphie, il faudra probablement vérifier les échecs. Mais une deuxième vérification sur les hameaux a un sens pour être sûr que tout fonctionne.

Cordialement

Corentin Faye

**Comment by canteaut** [comment]
Le 16/10/2019 à 14:42, Corentinfaye a écrit :
>
> Bonjour,
>
>     Je ne suis pas sûr de comprendre. Pourriez-vous donner un exemple ?
>
> Je me suis mal exprimé, je vous fais suivre l'exemple d'un canton et 
> d'un arrondissement. La question que je me pose est que le canton et 
> l'arrondissement mentionné correspond à un autre niveau administrative 
> donc on ne parle pas directement de la commune mais cela peut-être lié 
> à elle.
>
> |<definition><localisation>canton de Lembeye</localisation>.</definition>|
>
> |<definition><localisation>arrondissement d’Oloron</localisation>|
>
Sauf erreur de ma part, dans ce genre de cas, vous avez toujours affaire 
à une commune. Mais, comme souvent, le type "commune" n'est pas 
directement inscrit dans le fichier ; on le déduit du fait que le DT 
localise le lieu d'après le canton ou l'arrondissement.


>     Oui, liste à contrôler. Probablement des communes dans la majorité des
>     cas, mais ce n'est pas certain. La meilleure vérification consisterait
>     sans doute à regarder quelle(s) vedettes correspondent à ces noms :
>     nous récupérerions alors le n° INSEE qui leur est attaché, qu'il
>     s'agisse d'une commune ou d'un hameau localisé dans une commune ; en
>     revanche, il faudrait vérifier, car nous aurons en ce cas de nombreux
>     cas d'homonymie. Et l'ensemble est sans doute à faire tout à la fin,
>     quand tous les hameaux localisés se seront vus attribués un n° INSEE.
>
> Oui, je suis d'accord, un contrôle de ces entrées sur les vedettes du 
> tableau de correction doit permettre de vérifier si c'est une commune 
> ou non mais avec les possibles différences de graphie, il faudra 
> probablement vérifier les échecs. Mais une deuxième vérification sur 
> les hameaux a un sens pour être sûr que tout fonctionne.
>
Entendu, cela me semble la meilleure voie.

Bonne journée,

Olivier Canteaut

**Comment by Corentinfaye** [comment]
> Sauf erreur de ma part, dans ce genre de cas, vous avez toujours affaire
à une commune. Mais, comme souvent, le type "commune" n'est pas
directement inscrit dans le fichier ; on le déduit du fait que le DT
localise le lieu d'après le canton ou l'arrondissement.

Oui, il s'agit d'un nom de commune mais c'était pour être sûr que je mettes une balise commune à cette endroit car comme le nom de la commune rappelle pas directement la commune mais l'arrondissement dans lequel la commune est le chef-lieu.
Je mettrai donc une balise commune à cette endroit.

Cordialement,

Corentin Faye

**Comment by canteaut** [comment]
Là encore, je ne suis pas sûr de comprendre : nous sommes bien d'accord 
que, en ce cas, nous avons
|<article 
type="commune"><vedette>xxxxx</vedette><definition><localisation>canton 
de Lembeye</localisation>.</definition></article>|
et non
||<article><vedette>xxxxx</vedette><definition><localisation>canton de 
<commune>Lembeye</commune></localisation>.</definition></article>||

Cordialement,
Olivier Canteaut

Le 16/10/2019 à 17:38, Corentinfaye a écrit :

**Comment by architexte** [comment]
Implémenté dans le workflow
