### ISSUE TITLE
Contrôle du contenu des balises communes des différents DT

### ISSUE THREAD

**Issue by Corentinfaye** [chartes/dico-topo#20]
Les informations contenus dans les balises communes des DT doivent correspondre, dans la majorité des cas, aux labels INSEE.

Extraire les contenus des balises communes fautives et évaluer avec SN, OC et VJ quelles sont les balises qui doivent être modifier, supprimer ou conversever.

**Comment by architexte** [comment]
On maintient les noms des communes tels qu’imprimés dans les DT.
