### ISSUE TITLE
Procédure de reprise des outpu6.xml

### ISSUE THREAD

**Issue by Corentinfaye** [chartes/dico-topo#21]
- Contrôle des vedettes longues de plus de 30 caractères dans le terminal
- Remplacement des « precision="certaine" » par « precision ="certain" »
- Vérification de la segmentation des vedette/definition avec cet xpath : « //vedette//text()[not(ancestor::sm or parent::pg) and normalize-space(.)!=''] »
- Sortir les balises <pg> à l'intérieur des balises vedettes avec cette expression régulière : 
« <vedette>\n + (<pg>[0-9]+</pg>) » à remplacer par « $1\n<vedette> »
- Contrôle des inversions dans les balises localisatins avec les fichiers : « @DTXX_result_localisation_diff.csv» issue du script TestResultatDT.py

**Comment by architexte** [comment]
Documenté dans [documentation](https://github.com/chartes/dico-topo/blob/enrichissement_xml_dt/data/_OUTPUT6_VALDATION_PROCEDURE.md)
