### ISSUE TITLE
lever les codes d’erreur sur `localisation/commune`

### ISSUE THREAD

**Issue by architexte** [chartes/dico-topo#6]
L’indentification automatique des communes des localisations échoue à environ 10%.
TODO : lever les codes erreurs et renseigner dans la mesure du possible `@insee`.
Erreurs
1. `article_not_found`: le renvoi ne correspond à aucune vedette
1. `commune_is_empty`: la balise commune est vide
1. `insee_not_found`:  la vedette n’a pas de code insee
1. `too_many_insee_codes`: localisation correspondant à plusieurs vedettes

**Comment by architexte** [comment]
Réglé dans le worflow

**Comment by canteaut** [comment]
Salut,
Je vous vois faire plein de nettoyage, c'est super. Avez-vous du coup pu 
résoudre le souci étrange relevé par un utilisateur, à savoir que les 
lieux de la commune d'Urbise donnent tous une page blanche 
(https://dicotopo.cths.fr/places/P46509880 pour Urbise ; 
https://dicotopo.cths.fr/places/P09148122 pour un lieu sur la commune) ?
A+
Olivier

Le 31/01/2022 à 12:37, architexte a écrit :
